# Acid Acetic for fish
#
# Generated by acidify from ports/fish/acid.fish.tera. Do not edit; edit the
# template, or the palette in crates/acid-palette/src/lib.rs, and re-run
# `make ports`.
#
# These are global rather than universal variables, so the theme lives in
# tracked config and survives on any machine. Drop this in ~/.config/fish/conf.d
# and it applies on the next shell.

# Syntax highlighting
set -g fish_color_normal f2e9d0
set -g fish_color_command 2fe0b8
set -g fish_color_keyword ea7fc4
set -g fish_color_quote c9e02b
set -g fish_color_redirection ea7fc4
set -g fish_color_end ea7fc4
set -g fish_color_error ff4536
set -g fish_color_param f2e9d0
set -g fish_color_option 45b6ff
set -g fish_color_comment 6f6f6f --italics
set -g fish_color_operator ea7fc4
set -g fish_color_escape ff8b1f
set -g fish_color_autosuggestion 555555
set -g fish_color_cancel ff4536
set -g fish_color_gray 6f6f6f
set -g fish_color_selection f2e9d0 --background=3a3a3a
set -g fish_color_search_match --background=3a3a3a
set -g fish_color_match ffc832
set -g fish_color_valid_path --underline
set -g fish_color_history_current --bold

# Prompt
set -g fish_color_cwd 45b6ff
set -g fish_color_cwd_root ff4536
set -g fish_color_user 2fe0b8
set -g fish_color_host 45b6ff
set -g fish_color_host_remote ffc832
set -g fish_color_status ff4536

# Completion pager. The pager background is left unset so it inherits the
# terminal's own, which keeps a transparent terminal transparent.
set -g fish_pager_color_prefix 2fe0b8 --bold
set -g fish_pager_color_completion cdc7b8
set -g fish_pager_color_description 6f6f6f
set -g fish_pager_color_progress a8a49a --background=1e1e1e
set -g fish_pager_color_search_match --background=3a3a3a
set -g fish_pager_color_selected_background --background=3a3a3a
set -g fish_pager_color_selected_prefix 2fe0b8 --bold
set -g fish_pager_color_selected_completion f2e9d0
set -g fish_pager_color_selected_description a8a49a
set -g fish_pager_color_secondary_background --background=1e1e1e
set -g fish_pager_color_secondary_prefix 2fe0b8
set -g fish_pager_color_secondary_completion cdc7b8
set -g fish_pager_color_secondary_description 6f6f6f
