//! Starting a new port.
//!
//! A port is a folder, so this writes one: the manifest, a template, a README
//! and a test stub. The template and test are deliberately minimal — they are
//! meant to be replaced, not extended.

use std::{fs, path::Path};

use anyhow::{Context, Result, bail};

const TEMPLATE: &str = r#"# Acid {{ version }} — {{ flavor.name }}, for NAME
#
# Generated by acid from ports/NAME/theme.tera. Do not edit; edit the template,
# or the palette in crates/acid-palette/src/lib.rs, and re-run `make`.

background = "{{ flavor.colors.base }}"
foreground = "{{ flavor.colors.text }}"
comment    = "{{ flavor.colors.overlay1 }}"
"#;

const README: &str = r#"# Acid for TITLE

{{ flavours }}

Part of [Acid](https://github.com/{{ hub }}), a very dark colourscheme. The main
README lists the other ports.

{% if preview != "" %}## Preview

{{ preview }}

{% endif %}## Install

```sh
curl -fsSLo ~/.config/NAME/acid-acetic.conf \
  https://raw.githubusercontent.com/{{ hub }}/main/acid-acetic.conf
```

## Files

{{ files }}

## Generated

Acid {{ version }}, rendered by acid from
[`{{ template }}`](https://github.com/{{ hub }}/blob/main/{{ template }}).
Edits to these files are overwritten on the next release. Report issues on
[{{ hub }}](https://github.com/{{ hub }}/issues).

## Licence

MIT.
"#;

const TEST: &str = r#"// Check the theme with NAME's own program, so this reports what NAME accepts
// rather than what this file believes.

pub fn run(h: &mut Harness) -> anyhow::Result<()> {
    if !h.require(&["NAME"]) {
        return Ok(());
    }

    for flavour in h.flavours() {
        let theme = h.dist(&format!("acid-{}.conf", flavour.identifier));
        h.check(!read(&theme).is_empty(), format!("{}: the theme is not empty", flavour.identifier));
    }

    // Every test needs a control: a check that cannot fail proves nothing.
    h.fail("replace these checks, and give them a control");

    Ok(())
}
"#;

pub fn port(root: &Path, name: &str, title: &str) -> Result<()> {
    if !name
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
    {
        bail!("a port's name is lowercase letters, digits and hyphens: {name}");
    }

    let dir = root.join("ports").join(name);
    if dir.exists() {
        bail!("{} already exists", dir.display());
    }
    fs::create_dir_all(&dir).with_context(|| format!("cannot create {}", dir.display()))?;

    let manifest = format!(
        "title = {title:?}\ndescription = \"Acid for {title}. A very dark colourscheme.\"\n\n\
         # The packages this port's checks need.\n[test]\npackages = [{name:?}]\n\n\
         # Add a [preview] section and a preview.rs once the program renders\n\
         # headlessly; `acid check` requires the two together or neither.\n\n\
         [render]\nmatrix = [\"flavor\"]\nfilename = \"dist/acid-{{flavor}}.conf\"\n"
    );
    fs::write(dir.join("port.toml"), manifest)?;
    fs::write(dir.join("theme.tera"), TEMPLATE.replace("NAME", name))?;
    fs::write(
        dir.join("README.tera"),
        README.replace("NAME", name).replace("TITLE", title),
    )?;
    fs::write(dir.join("test.rs"), TEST.replace("NAME", name))?;

    println!("created {}", dir.display());
    println!("  port.toml    what the port is");
    println!("  theme.tera   the theme, rendered once per flavour");
    println!("  README.tera  the port's own README");
    println!("  test.rs      replace the stub, and give it a control");
    println!("\nthen: make && acid test {name}");
    Ok(())
}
