# Acid 0.1.0 — Acetic, for qutebrowser
#
# Generated by acidify from ports/qutebrowser/acid.py.tera. Do not edit; edit the
# template, or the palette in crates/acid-palette/src/lib.rs, and re-run
# `make ports`.
#
# Pull it in from config.py, which runs it with `c` already bound:
#
#     config.source("acid-acetic.py")

# Completion
c.colors.completion.fg = "#f2e9d0"
c.colors.completion.odd.bg = "#0f0f0f"
c.colors.completion.even.bg = "#000000"
c.colors.completion.category.fg = "#ffc832"
c.colors.completion.category.bg = "#242424"
c.colors.completion.category.border.top = "#242424"
c.colors.completion.category.border.bottom = "#242424"
c.colors.completion.item.selected.fg = "#f2e9d0"
c.colors.completion.item.selected.bg = "#4a4a4a"
c.colors.completion.item.selected.border.top = "#4a4a4a"
c.colors.completion.item.selected.border.bottom = "#4a4a4a"
c.colors.completion.item.selected.match.fg = "#2fe0b8"
c.colors.completion.match.fg = "#2fe0b8"
c.colors.completion.scrollbar.fg = "#5a5a5a"
c.colors.completion.scrollbar.bg = "#242424"

# Context menu and tooltips
c.colors.contextmenu.menu.bg = "#242424"
c.colors.contextmenu.menu.fg = "#f2e9d0"
c.colors.contextmenu.selected.bg = "#4a4a4a"
c.colors.contextmenu.selected.fg = "#f2e9d0"
c.colors.contextmenu.disabled.bg = "#242424"
c.colors.contextmenu.disabled.fg = "#5a5a5a"
c.colors.tooltip.bg = "#242424"
c.colors.tooltip.fg = "#f2e9d0"

# Downloads
c.colors.downloads.bar.bg = "#0f0f0f"
c.colors.downloads.start.fg = "#000000"
c.colors.downloads.start.bg = "#45b6ff"
c.colors.downloads.stop.fg = "#000000"
c.colors.downloads.stop.bg = "#c9e02b"
c.colors.downloads.error.fg = "#000000"
c.colors.downloads.error.bg = "#ff4536"

# Hints
c.colors.hints.fg = "#000000"
c.colors.hints.bg = "#ffc832"
c.colors.hints.match.fg = "#ff4536"

# Key hints
c.colors.keyhint.fg = "#f2e9d0"
c.colors.keyhint.suffix.fg = "#ffc832"
c.colors.keyhint.bg = "#242424"

# Messages: informational, then escalating
c.colors.messages.info.fg = "#000000"
c.colors.messages.info.bg = "#45b6ff"
c.colors.messages.info.border = "#45b6ff"
c.colors.messages.warning.fg = "#000000"
c.colors.messages.warning.bg = "#ff8b1f"
c.colors.messages.warning.border = "#ff8b1f"
c.colors.messages.error.fg = "#000000"
c.colors.messages.error.bg = "#ff4536"
c.colors.messages.error.border = "#ff4536"

# Prompts
c.colors.prompts.fg = "#f2e9d0"
c.colors.prompts.bg = "#242424"
c.colors.prompts.border = "1px solid #4a4a4a"
c.colors.prompts.selected.fg = "#f2e9d0"
c.colors.prompts.selected.bg = "#4a4a4a"

# Status bar: the mode is the background colour
c.colors.statusbar.normal.fg = "#f2e9d0"
c.colors.statusbar.normal.bg = "#0f0f0f"
c.colors.statusbar.insert.fg = "#000000"
c.colors.statusbar.insert.bg = "#c9e02b"
c.colors.statusbar.passthrough.fg = "#000000"
c.colors.statusbar.passthrough.bg = "#45b6ff"
c.colors.statusbar.private.fg = "#000000"
c.colors.statusbar.private.bg = "#ea7fc4"
c.colors.statusbar.command.fg = "#f2e9d0"
c.colors.statusbar.command.bg = "#242424"
c.colors.statusbar.command.private.fg = "#f2e9d0"
c.colors.statusbar.command.private.bg = "#383838"
c.colors.statusbar.caret.fg = "#000000"
c.colors.statusbar.caret.bg = "#ea7fc4"
c.colors.statusbar.caret.selection.fg = "#000000"
c.colors.statusbar.caret.selection.bg = "#2fe0b8"
c.colors.statusbar.progress.bg = "#45b6ff"

# The URL, which reports the state of the page
c.colors.statusbar.url.fg = "#f2e9d0"
c.colors.statusbar.url.hover.fg = "#2fe0b8"
c.colors.statusbar.url.success.http.fg = "#ff8b1f"
c.colors.statusbar.url.success.https.fg = "#c9e02b"
c.colors.statusbar.url.warn.fg = "#ffc832"
c.colors.statusbar.url.error.fg = "#ff4536"

# Tabs
c.colors.tabs.bar.bg = "#1c1c1c"
c.colors.tabs.indicator.start = "#45b6ff"
c.colors.tabs.indicator.stop = "#c9e02b"
c.colors.tabs.indicator.error = "#ff4536"
c.colors.tabs.odd.fg = "#a49f95"
c.colors.tabs.odd.bg = "#0f0f0f"
c.colors.tabs.even.fg = "#a49f95"
c.colors.tabs.even.bg = "#0f0f0f"
c.colors.tabs.selected.odd.fg = "#f2e9d0"
c.colors.tabs.selected.odd.bg = "#242424"
c.colors.tabs.selected.even.fg = "#f2e9d0"
c.colors.tabs.selected.even.bg = "#242424"
c.colors.tabs.pinned.odd.fg = "#a49f95"
c.colors.tabs.pinned.odd.bg = "#383838"
c.colors.tabs.pinned.even.fg = "#a49f95"
c.colors.tabs.pinned.even.bg = "#383838"
c.colors.tabs.pinned.selected.odd.fg = "#f2e9d0"
c.colors.tabs.pinned.selected.odd.bg = "#4a4a4a"
c.colors.tabs.pinned.selected.even.fg = "#f2e9d0"
c.colors.tabs.pinned.selected.even.bg = "#4a4a4a"

# The page itself, shown before a site paints its own background
c.colors.webpage.bg = "#000000"
c.colors.webpage.preferred_color_scheme = "dark"
