# Acid 0.1.0 — Citric, for qutebrowser
#
# Generated by acidify from ports/qutebrowser/acid.py.tera. Do not edit; edit the
# template, or the palette in crates/acid-palette/src/lib.rs, and re-run
# `make ports`.
#
# Pull it in from config.py, which runs it with `c` already bound:
#
#     config.source("acid-citric.py")

# Completion
c.colors.completion.fg = "#e2d6b6"
c.colors.completion.odd.bg = "#121211"
c.colors.completion.even.bg = "#1c1b19"
c.colors.completion.category.fg = "#d9a441"
c.colors.completion.category.bg = "#35332c"
c.colors.completion.category.border.top = "#35332c"
c.colors.completion.category.border.bottom = "#35332c"
c.colors.completion.item.selected.fg = "#e2d6b6"
c.colors.completion.item.selected.bg = "#5b554a"
c.colors.completion.item.selected.border.top = "#5b554a"
c.colors.completion.item.selected.border.bottom = "#5b554a"
c.colors.completion.item.selected.match.fg = "#7cad76"
c.colors.completion.match.fg = "#7cad76"
c.colors.completion.scrollbar.fg = "#6b665c"
c.colors.completion.scrollbar.bg = "#35332c"

# Context menu and tooltips
c.colors.contextmenu.menu.bg = "#35332c"
c.colors.contextmenu.menu.fg = "#e2d6b6"
c.colors.contextmenu.selected.bg = "#5b554a"
c.colors.contextmenu.selected.fg = "#e2d6b6"
c.colors.contextmenu.disabled.bg = "#35332c"
c.colors.contextmenu.disabled.fg = "#6b665c"
c.colors.tooltip.bg = "#35332c"
c.colors.tooltip.fg = "#e2d6b6"

# Downloads
c.colors.downloads.bar.bg = "#121211"
c.colors.downloads.start.fg = "#1c1b19"
c.colors.downloads.start.bg = "#7d9cba"
c.colors.downloads.stop.fg = "#1c1b19"
c.colors.downloads.stop.bg = "#a3ab2f"
c.colors.downloads.error.fg = "#1c1b19"
c.colors.downloads.error.bg = "#de5a48"

# Hints
c.colors.hints.fg = "#1c1b19"
c.colors.hints.bg = "#d9a441"
c.colors.hints.match.fg = "#de5a48"

# Key hints
c.colors.keyhint.fg = "#e2d6b6"
c.colors.keyhint.suffix.fg = "#d9a441"
c.colors.keyhint.bg = "#35332c"

# Messages: informational, then escalating
c.colors.messages.info.fg = "#1c1b19"
c.colors.messages.info.bg = "#7d9cba"
c.colors.messages.info.border = "#7d9cba"
c.colors.messages.warning.fg = "#1c1b19"
c.colors.messages.warning.bg = "#dd7b34"
c.colors.messages.warning.border = "#dd7b34"
c.colors.messages.error.fg = "#1c1b19"
c.colors.messages.error.bg = "#de5a48"
c.colors.messages.error.border = "#de5a48"

# Prompts
c.colors.prompts.fg = "#e2d6b6"
c.colors.prompts.bg = "#35332c"
c.colors.prompts.border = "1px solid #5b554a"
c.colors.prompts.selected.fg = "#e2d6b6"
c.colors.prompts.selected.bg = "#5b554a"

# Status bar: the mode is the background colour
c.colors.statusbar.normal.fg = "#e2d6b6"
c.colors.statusbar.normal.bg = "#121211"
c.colors.statusbar.insert.fg = "#1c1b19"
c.colors.statusbar.insert.bg = "#a3ab2f"
c.colors.statusbar.passthrough.fg = "#1c1b19"
c.colors.statusbar.passthrough.bg = "#7d9cba"
c.colors.statusbar.private.fg = "#1c1b19"
c.colors.statusbar.private.bg = "#c5839c"
c.colors.statusbar.command.fg = "#e2d6b6"
c.colors.statusbar.command.bg = "#35332c"
c.colors.statusbar.command.private.fg = "#e2d6b6"
c.colors.statusbar.command.private.bg = "#49443b"
c.colors.statusbar.caret.fg = "#1c1b19"
c.colors.statusbar.caret.bg = "#c5839c"
c.colors.statusbar.caret.selection.fg = "#1c1b19"
c.colors.statusbar.caret.selection.bg = "#7cad76"
c.colors.statusbar.progress.bg = "#7d9cba"

# The URL, which reports the state of the page
c.colors.statusbar.url.fg = "#e2d6b6"
c.colors.statusbar.url.hover.fg = "#7cad76"
c.colors.statusbar.url.success.http.fg = "#dd7b34"
c.colors.statusbar.url.success.https.fg = "#a3ab2f"
c.colors.statusbar.url.warn.fg = "#d9a441"
c.colors.statusbar.url.error.fg = "#de5a48"

# Tabs
c.colors.tabs.bar.bg = "#060605"
c.colors.tabs.indicator.start = "#7d9cba"
c.colors.tabs.indicator.stop = "#a3ab2f"
c.colors.tabs.indicator.error = "#de5a48"
c.colors.tabs.odd.fg = "#b4ab9b"
c.colors.tabs.odd.bg = "#121211"
c.colors.tabs.even.fg = "#b4ab9b"
c.colors.tabs.even.bg = "#121211"
c.colors.tabs.selected.odd.fg = "#e2d6b6"
c.colors.tabs.selected.odd.bg = "#35332c"
c.colors.tabs.selected.even.fg = "#e2d6b6"
c.colors.tabs.selected.even.bg = "#35332c"
c.colors.tabs.pinned.odd.fg = "#b4ab9b"
c.colors.tabs.pinned.odd.bg = "#49443b"
c.colors.tabs.pinned.even.fg = "#b4ab9b"
c.colors.tabs.pinned.even.bg = "#49443b"
c.colors.tabs.pinned.selected.odd.fg = "#e2d6b6"
c.colors.tabs.pinned.selected.odd.bg = "#5b554a"
c.colors.tabs.pinned.selected.even.fg = "#e2d6b6"
c.colors.tabs.pinned.selected.even.bg = "#5b554a"

# The page itself, shown before a site paints its own background
c.colors.webpage.bg = "#1c1b19"
c.colors.webpage.preferred_color_scheme = "dark"
